version: '3.1'

services:

  prometheus:
    image: prom/prometheus
    volumes:
      - /swarm/volumes/prometheus/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    resources:
        limits:
          memory: 512M
    depends_on:
      - cadvisor
    deploy:
      restart_policy:
        condition: on-failure

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - "/swarm/volumes/prometheus/alertmanager/:/etc/alertmanager/"
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    deploy:
      restart_policy:
        condition: on-failure

  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    deploy:
      mode: global

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - /swarm/volumes/prometheus/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - /swarm/volumes/prometheus/grafana/config.monitoring
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  prometheus_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.2
      device: ":/export/NFS/prometheus/prometheus/data"

  grafana_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.2
      device: ":/export/NFS/prometheus/grafana/data"
