metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: true
    reload.period: 10s

output.logstash:
  hosts: ["logstash:5044"]