# Use root/example as user/password credentials

version: '3.1'

services:

  adminer:
    image: adminer
    env_file:
      - .env
    ports:
      - 8000:8080
#    environment:
#      - ADMINER_DEFAULT_SERVER=mariadb
    networks:
      - marianet

networks:
 marianet:
  external: true
