version: '3'
services:
  netdata:
    image: netdata/netdata
    hostname: proxy.local
    environment:
      - PUID=1000
      - PGID=999
    ports:
      - 19999:19999
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
